// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbbL8JlS7moT2icgjcz8mKcro0V77cNVo',
    appId: '1:297130269711:web:83a8b240f826dbada0177a',
    messagingSenderId: '297130269711',
    projectId: 'flutter-chat-ttcs',
    authDomain: 'flutter-chat-ttcs.firebaseapp.com',
    storageBucket: 'flutter-chat-ttcs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwk-zJlP-_6Yb2AR9XRR5rDIY75Qs5jNs',
    appId: '1:297130269711:android:93ae693577e07352a0177a',
    messagingSenderId: '297130269711',
    projectId: 'flutter-chat-ttcs',
    storageBucket: 'flutter-chat-ttcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LKew75fIMcoQi-vfZqo0uRzibBtLzLI',
    appId: '1:297130269711:ios:7b71b459e8660dc2a0177a',
    messagingSenderId: '297130269711',
    projectId: 'flutter-chat-ttcs',
    storageBucket: 'flutter-chat-ttcs.appspot.com',
    iosBundleId: 'com.example.chatAppTtcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LKew75fIMcoQi-vfZqo0uRzibBtLzLI',
    appId: '1:297130269711:ios:7b71b459e8660dc2a0177a',
    messagingSenderId: '297130269711',
    projectId: 'flutter-chat-ttcs',
    storageBucket: 'flutter-chat-ttcs.appspot.com',
    iosBundleId: 'com.example.chatAppTtcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbbL8JlS7moT2icgjcz8mKcro0V77cNVo',
    appId: '1:297130269711:web:3f4ab3d785feb9b5a0177a',
    messagingSenderId: '297130269711',
    projectId: 'flutter-chat-ttcs',
    authDomain: 'flutter-chat-ttcs.firebaseapp.com',
    storageBucket: 'flutter-chat-ttcs.appspot.com',
  );

}